docs_dir: ./docs
site_name: Frontend starter app

nav:
  - Home: index.md
  - 'Frontend Operator':
    - Overview: /frontend-operator/index.md
    - 'Basic configuration': ./frontend-operator/basic-configuration.md
    - 'UI module configuration': ./frontend-operator/modules.md
    - Navigation: ./frontend-operator//navigation.md
    - 'Services dropdown': ./frontend-operator/services.md
    - Search: ./frontend-operator//search.md
