# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json
---
apiVersion: v1
kind: Template
metadata:
  name: frontend-starter-app
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: frontend-starter-app
    spec:
      feoConfigEnabled: true
      serviceTiles:
        - id: starter-link
          section: automation
          group: ansible
          title: Starter app FEO integration testing tile
          href: /staging/starter
          description: This tile will not show in production and exists only for integration testing purposes
          icon: AnsibleIcon
      searchEntries:
        - id: "starter"
          title: "Starter app FEO testing link"
          href: /staging/foo/starter
          description: "An experimental link to test FEO features integration"
          alt_title:
            - Starter
            - Starter app
      bundleSegments:
        - segmentId: starter-app-two
          bundleId: staging
          position: 200
          navItems:
            - id: frontend-starter-app-two
              title: Starter app link two
              href: /staging/foo/starter
        - segmentId: starter-app
          bundleId: staging
          position: 100
          navItems:
            - id: frontend-starter-app
              title: Starter app link
              href: /staging/starter
      API:
        versions:
          - v1
      envName: ${ENV_NAME}
      title: Starter App
      deploymentRepo: https://github.com/RedHatInsights/frontend-starter-app
      frontend:
        paths:
          - /apps/frontend-starter-app
      image: ${IMAGE}:${IMAGE_TAG}

      module:
        manifestLocation: '/apps/frontend-starter-app/fed-mods.json'
        modules:
          - id: 'overview'
            module: './RootApp'
            routes:
              - pathname: /staging/starter
          - id: 'feo-hidden-route'
            module: './RootApp'
            routes:
              - pathname: /staging/foo/starter

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/frontend-starter-app
