# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json
---
apiVersion: v1
kind: Template
metadata:
  name: cloud-inventory
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: cloud-inventory
    spec:
      feoConfigEnabled: true
      searchEntries:
        - id: "cloud-inventory"
          title: "Cloud Inventory"
          href: /subscriptions/cloud-inventory
          description: "Manage your cloud subscriptions"
          alt_title:
            - Cloud Inventory
      bundleSegments:
        - segmentId: cloud-inventory
          bundleId: staging
          position: 100
          navItems:
            - id: cloud-inventory
              title: Cloud Inventory
              href: /subscriptions/cloud-inventory
      API:
        versions:
          - v1
      envName: ${ENV_NAME}
      title: Cloud Inventory
      deploymentRepo: https://github.com/RedHatInsights/cloud-inventory-ui
      frontend:
        paths:
          - /apps/cloud-inventory
      image: ${IMAGE}:${IMAGE_TAG}

      module:
        manifestLocation: '/apps/cloud-inventory/fed-mods.json'
        modules:
          - id: 'cloud-inventory'
            module: './RootApp'
            routes:
              - pathname: /subscriptions/cloud-inventory

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/cloud-inventory-ui
